    sources:
      - Jaldi.glyphs
    axisOrder:
      - wght
    familyName: Jaldi
    stat:
      Jaldi[wght].ttf:
      - name: Weight
        tag: wght
        values:
        - name: Regular
          value: 400
          linkedValue: 700
          flags: 2
        - name: Bold
          value: 700